# Generated by Django 6.0.4 on 2026-05-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Fornecedor',
                'verbose_name_plural': 'Categorias de Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social ou Nome')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('document_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='Status')),
                ('categories', models.ManyToManyField(blank=True, related_name='suppliers', to='suppliers.suppliercategory', verbose_name='Categorias de fornecimento')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['legal_name'],
            },
        ),
    ]
