# Generated by Django 6.0.4 on 2026-05-02 02:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('expected_start_date', models.DateField(blank=True, null=True, verbose_name='Data prevista de início')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='Data prevista de término')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('closed', 'Encerrada'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='Status')),
                ('expected_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor previsto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField(verbose_name='Data')),
                ('weather', models.CharField(blank=True, max_length=120, null=True, verbose_name='Clima')),
                ('team_present', models.TextField(blank=True, null=True, verbose_name='Equipe presente')),
                ('services_performed', models.TextField(verbose_name='Serviços executados')),
                ('occurrences', models.TextField(blank=True, null=True, verbose_name='Ocorrências')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Diário de Obra',
                'verbose_name_plural': 'Diários de Obra',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Serviço ou etapa')),
                ('planned_start_date', models.DateField(verbose_name='Início planejado')),
                ('planned_end_date', models.DateField(verbose_name='Término planejado')),
                ('planned_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual planejado')),
                ('planned_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Custo planejado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Tarefa da Obra',
                'verbose_name_plural': 'Tarefas da Obra',
                'ordering': ['planned_start_date', 'planned_end_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_date', models.DateField(verbose_name='Data da medição')),
                ('measured_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual medido')),
                ('measured_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor medido')),
                ('visible_in_portal', models.BooleanField(default=False, verbose_name='Visível no Portal do Cliente')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='projects.projecttask')),
            ],
            options={
                'verbose_name': 'Medição Física',
                'verbose_name_plural': 'Medições Físicas',
                'ordering': ['-measurement_date', '-created_at'],
            },
        ),
    ]
