# Generated by Django 6.0.4 on 2026-05-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('projects', '0001_initial'),
        ('purchases', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='open', max_length=20, verbose_name='Status')),
                ('source_label', models.CharField(default='Lançamento manual', max_length=255, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payable', to='projects.project')),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_payable', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_payable', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('received', 'Recebido'), ('cancelled', 'Cancelado')], default='open', max_length=20, verbose_name='Status')),
                ('source_label', models.CharField(default='Faturamento manual', max_length=255, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='customers.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='projects.project')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=20, verbose_name='Tipo')),
                ('transaction_date', models.DateField(verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('account_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.accountpayable')),
                ('account_receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.accountreceivable')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
