# Generated by Django 6.0.4 on 2026-05-02 10:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='billing_type',
            field=models.CharField(choices=[('admin', 'Administração de obra'), ('measurement', 'Medição física'), ('progress_fee', 'Taxa por avanço físico'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Tipo de faturamento'),
        ),
        migrations.CreateModel(
            name='InvoiceXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xml_file', models.FileField(upload_to='finance/invoices/', verbose_name='XML original')),
                ('access_key', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de acesso')),
                ('issuer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Emitente')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor total')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_xmls', to='projects.project')),
            ],
            options={
                'verbose_name': 'NFe XML',
                'verbose_name_plural': 'NFe XMLs',
                'ordering': ['-imported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAppropriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=255, verbose_name='Serviço')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor apropriado')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_appropriations', to='projects.project')),
                ('invoice_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appropriations', to='finance.invoicexml')),
            ],
            options={
                'verbose_name': 'Apropriação Financeira',
                'verbose_name_plural': 'Apropriações Financeiras',
                'ordering': ['project__name', 'service_name', '-created_at'],
            },
        ),
    ]
