# Generated by Django 6.0.4 on 2026-05-02 10:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('quoted', 'Cotada'), ('ordered', 'Ordenada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='projects.project')),
            ],
            options={
                'verbose_name': 'Solicitação de Compra',
                'verbose_name_plural': 'Solicitações de Compra',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchases.purchaserequest')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantidade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('input_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_items', to='budgets.inputitem')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserequest')),
            ],
            options={
                'verbose_name': 'Item Solicitado',
                'verbose_name_plural': 'Itens Solicitados',
                'ordering': ['created_at', 'description'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
                ('purchase_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='purchases.purchaserequestitem')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Compra',
                'verbose_name_plural': 'Itens da Ordem de Compra',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('responded', 'Respondida'), ('finished', 'Finalizada')], default='open', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='purchases.purchaserequest')),
                ('winner_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_quotations', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchases.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Convidado'), ('responded', 'Respondido'), ('declined', 'Recusado')], default='invited', max_length=20, verbose_name='Status')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='purchases.quotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_invites', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Fornecedor Convidado',
                'verbose_name_plural': 'Fornecedores Convidados',
                'ordering': ['supplier__legal_name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('purchase_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_prices', to='purchases.purchaserequestitem')),
                ('quotation_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='purchases.quotationsupplier')),
            ],
            options={
                'verbose_name': 'Preço por Item',
                'verbose_name_plural': 'Preços por Item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotationsupplier',
            constraint=models.UniqueConstraint(fields=('quotation', 'supplier'), name='unique_quotation_supplier'),
        ),
        migrations.AddConstraint(
            model_name='quotationitemprice',
            constraint=models.UniqueConstraint(fields=('quotation_supplier', 'purchase_request_item'), name='unique_quotation_item_price'),
        ),
    ]
