# Generated by Django 6.0.4 on 2026-05-02 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('person_type', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('document_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to='customer_documents/%Y/%m/', verbose_name='Arquivo')),
                ('visible_in_portal', models.BooleanField(default=False, verbose_name='Visível no Portal do Cliente')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos do Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('call', 'Ligação'), ('email', 'Email'), ('meeting', 'Reunião'), ('whatsapp', 'WhatsApp'), ('other', 'Outro')], default='call', max_length=20, verbose_name='Tipo de Interação')),
                ('interaction_date', models.DateField(verbose_name='Data da Interação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação com Cliente',
                'verbose_name_plural': 'Interações com Clientes',
                'ordering': ['-interaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='customer_photos/%Y/%m/', verbose_name='Imagem')),
                ('visible_in_portal', models.BooleanField(default=False, verbose_name='Visível no Portal do Cliente')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Foto do Cliente',
                'verbose_name_plural': 'Fotos do Cliente',
                'ordering': ['-created_at'],
            },
        ),
    ]
